#!/usr/bin/env node
// Concentric-square bed levelling test, one layer tall.
//
//   node tools/bedlevel.js [outdir]
//
// Prints as a set of single-layer frames spread from the middle of the plate out to
// near its edges. Read the squish: a ring that is glassy and wide is over-squished, one
// that is rounded, narrow or peeling is under-squished. Because the frames are
// concentric you also get the LEFT-versus-RIGHT and FRONT-versus-BACK comparison on the
// same ring, which is what tells you about tilt rather than about nozzle height.
//
// SIZED FOR THE MACHINE THIS IS FOR - a Creality K1 Max at 0.6 nozzle, 0.3 layer:
//
//   HEIGHT is 0.30mm, exactly one layer. Not 0.2 and not "thin" - a test artifact
//   thinner than the layer height gets rounded up or dropped at slice time, which is
//   the trap PR-16's 0.15mm standoff fell into.
//
//   WIDTH is 1.20mm, exactly two 0.6mm beads. A single-bead frame reads squish more
//   directly but relies on the slicer's thin-wall handling; two beads slice
//   predictably anywhere and still show under-squish as a visible gap down the middle.
//
//   OUTER FRAME is 290mm, not 300. Creality Print refuses to place real geometry at
//   297.6mm on this bed - measured, bracketed at 296.1 rejected / 294.6 accepted - so
//   290 leaves margin without giving up the edges, which are the part you care about.
//
// Each frame is emitted as its own closed manifold shell. They do not touch, so there
// is no coincident-face geometry and each ring peels off independently for inspection.

const fs = require('fs');
const path = require('path');

const outdir = process.argv[2] || path.join(__dirname, '..', 'stl', 'test');

const H = 0.30;            // mm - one layer
const W = 1.20;            // mm - two 0.6 beads
const FRAMES = [290, 230, 170, 110, 50];
const CENTRE = 20;         // filled patch in the middle, the reference square
const KEY = 10;            // filled orientation key, front-left

const tri = [];
const push = (n, a, b, c) => tri.push([n, a, b, c]);

// A box as 12 triangles with outward normals.
function box(x0, x1, y0, y1, z0, z1) {
  const v = [
    [x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0],
    [x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1],
  ];
  const q = (a, b, c, d, n) => { push(n, v[a], v[b], v[c]); push(n, v[a], v[c], v[d]); };
  q(0, 3, 2, 1, [0, 0, -1]);   // bottom
  q(4, 5, 6, 7, [0, 0, 1]);    // top
  q(0, 1, 5, 4, [0, -1, 0]);
  q(1, 2, 6, 5, [1, 0, 0]);
  q(2, 3, 7, 6, [0, 1, 0]);
  q(3, 0, 4, 7, [-1, 0, 0]);
}

// A square frame as ONE closed shell: an annulus prism.
//
// Not four bars. Four abutting boxes share their touching faces, and a shared face
// means edges with four triangles on them - 20 non-manifold edges across five frames,
// which is what the first version of this did. Build the ring directly instead: top
// and bottom annulus faces, an outer wall and an inner wall, no internal geometry.
function frame(size, w, h) {
  const o = size / 2, i = o - w;
  const O = [[-o, -o], [o, -o], [o, o], [-o, o]];   // outer, counter-clockwise
  const I = [[-i, -i], [i, -i], [i, i], [-i, i]];   // inner, same order
  const at = (p, z) => [p[0], p[1], z];
  const quad = (a, b, c, d, n) => { push(n, a, b, c); push(n, a, c, d); };

  for (let k = 0; k < 4; k++) {
    const j = (k + 1) % 4;
    // top and bottom annulus faces
    quad(at(O[k], h), at(O[j], h), at(I[j], h), at(I[k], h), [0, 0, 1]);
    quad(at(O[k], 0), at(I[k], 0), at(I[j], 0), at(O[j], 0), [0, 0, -1]);
    // outer wall, facing away from centre
    const on = [O[j][1] - O[k][1], O[k][0] - O[j][0], 0];
    quad(at(O[k], 0), at(O[j], 0), at(O[j], h), at(O[k], h), on);
    // inner wall, facing into the hole
    quad(at(I[k], 0), at(I[k], h), at(I[j], h), at(I[j], 0), [-on[0], -on[1], 0]);
  }
}

for (const s of FRAMES) frame(s, W, H);
box(-CENTRE / 2, CENTRE / 2, -CENTRE / 2, CENTRE / 2, 0, H);        // centre patch
box(-130, -130 + KEY, -130, -130 + KEY, 0, H);                      // orientation key

// ---- binary STL ----
const buf = Buffer.alloc(84 + tri.length * 50);
buf.write('bed-level test - concentric squares - generated by tools/bedlevel.js', 0, 'latin1');
buf.writeUInt32LE(tri.length, 80);
let o = 84;
for (const [n, a, b, c] of tri) {
  for (const val of [...n, ...a, ...b, ...c]) { buf.writeFloatLE(val, o); o += 4; }
  buf.writeUInt16LE(0, o); o += 2;
}
fs.mkdirSync(outdir, { recursive: true });
const file = path.join(outdir, 'bed-level-squares.stl');
fs.writeFileSync(file, buf);

const span = FRAMES[0];
console.log(path.relative(path.join(__dirname, '..'), file));
console.log(`  ${FRAMES.length} frames ${FRAMES.join(', ')} mm + a ${CENTRE}mm centre patch + a ${KEY}mm key`);
console.log(`  ${W.toFixed(2)} mm wide, ${H.toFixed(2)} mm tall, ${tri.length} triangles`);
console.log(`  footprint ${span} x ${span} mm - ${(300 - span) / 2} mm clear each side of a 300 bed`);
